name: PHP-FPM Docker Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    environment: docker
    strategy:
      matrix:
        image-namespace: [wataly]
        image-name: [actions]
        image-version: [php-fpm]

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Build Image
      env:
        docker_username: ${{ secrets.DOCKER_HUB_ID }}
        docker_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      run: |
        cd docker
        sudo docker login --username=${docker_username} --password=${docker_password}
        sudo export PHP_VERSION=7.2 && docker-compose build --no-cache php-fpm
        sudo docker push wataly/php:$PHP_VERSION
        sudo export PHP_VERSION=7.3 && docker-compose build --no-cache php-fpm
        sudo docker push wataly/php:$PHP_VERSION
        sudo export PHP_VERSION=7.4 && docker-compose build --no-cache php-fpm
        sudo docker push wataly/php:$PHP_VERSION